# Generated by Django 4.2.1 on 2023-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='ambit',
        ),
        migrations.RemoveField(
            model_name='member',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='member',
            name='estil',
        ),
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
        migrations.RemoveField(
            model_name='member',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
        migrations.AddField(
            model_name='member',
            name='board_games',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='degree',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='music',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='read',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sport',
            field=models.IntegerField(null=True),
        ),
    ]
