# Generated by Django 4.2.1 on 2023-05-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cluster',
            field=models.IntegerField(null=True),
        ),
    ]
